<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="XAV-101000615" name="com.xavient.framework.WebApplicationSuite.menu_management_search" tests="1" failures="1" timestamp="5 Sep 2016 07:41:14 GMT" time="65.851" errors="0">
  <testcase name="menu_management_search" time="65.851" classname="com.xavient.framework.WebApplicationSuite.menu_management_search">
    <failure type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.xavient.framework.util.Keywords_reflection.executeKeywords(Keywords_reflection.java:124)
	at com.xavient.framework.WebApplicationSuite.menu_management_search.menu_management_search(menu_management_search.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.xavient.framework.util.Keywords_reflection.takeScreenShot(Keywords_reflection.java:461)
	at com.xavient.framework.util.Keywords_reflection.reportError(Keywords_reflection.java:407)
	at com.xavient.framework.util.Keywords_reflection.openBrowser(Keywords_reflection.java:182)
	... 19 more
]]>
    </failure>
  </testcase>
</testsuite>
